# -*- coding: utf-8 -*-
"""SAM_Mask_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Hersheys19/ME5920-Assignment2/blob/main/SAM_Mask_generation.ipynb
"""

!pip install git+https://github.com/facebookresearch/segment-anything.git
!pip install opencv-python matplotlib

!wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt
import os
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

device = "cuda" if torch.cuda.is_available() else "cpu"
sam_checkpoint = "sam_vit_h_4b8939.pth"
model_type = "vit_h"

print(f"Loading model to {device}...")
sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
sam.to(device=device)

mask_generator = SamAutomaticMaskGenerator(
    model=sam,
    points_per_side=64,
    pred_iou_thresh=0.86,
    stability_score_thresh=0.92,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=100,
)

def show_anns(anns):
    if len(anns) == 0:
        return
    sorted_anns = sorted(anns, key=(lambda x: x['area']), reverse=True)
    ax = plt.gca()
    ax.set_autoscale_on(False)

    img = np.zeros((sorted_anns[0]['segmentation'].shape[0], sorted_anns[0]['segmentation'].shape[1], 4))
    for ann in sorted_anns:
        m = ann['segmentation']
        color_mask = np.concatenate([np.random.random(3), [0.7]])
        img[m] = color_mask
    ax.imshow(img)

image_paths = ["sam_1.jpeg", "sam_2.jpg", "sam_3.jpeg", "sam_4.jpg", "sam_5.jpg", "sam_6.jpg", "sam_7.jpg", "sam_8.jpg", "sam_9.jpg", "sam_10.jpg", "sam_11.jpg", "sam_12.jpg"]

for path in image_paths:
    if not os.path.exists('sam_images/' + path):
        print(f"Skipping {path}: File not found.")
        continue

    image = cv2.imread('sam_images/' + path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    h, w = image.shape[:2]
    if max(h, w) > 1024:
        scale = 1024 / max(h, w)
        image = cv2.resize(image, (int(w * scale), int(h * scale)))

    print(f"Processing {path}...")

    masks = mask_generator.generate(image)

    plt.figure(figsize=(10, 10))
    plt.imshow(image)
    show_anns(masks)
    plt.axis('off')
    plt.title(f"Image: {path} | Masks Found: {len(masks)}")
    plt.show()

    print(f"Total masks for {path}: {len(masks)}\n" + "-"*30)

"""The Segment Anything Model (SAM) demonstrated high boundary precision in high-contrast environments, such as the museum and traffic scenes, where it successfully captured intricate structural details. However, in scenes characterized by high visual complexity and overlapping instances—notably the industrial machinery—the model exhibited a tendency toward over-segmentation. This resulted in a failure to maintain global semantic coherence, as the model prioritized local features over the unified object. Similarly, in biological subjects (humans and animals), SAM occasionally discretized anatomical components into independent masks. In the agricultural imagery, while the model achieved high recall for individual details, it struggled to consolidate these into a singular, comprehensive segment, highlighting a trade-off between local granularity and holistic object recognition.

Comparative analysis reveals a significant performance degradation when utilizing the ViT-B (Base) variant of SAM relative to the larger backbones. The reduced parameter count in the ViT-B architecture creates a representational bottleneck, limiting the model's ability to encode high-frequency spatial details. Consequently, the model failed to achieve adequate segmentation recall, entirely omitting smaller objects and producing coarse boundaries in complex scenes. This suggests that the reduced latent space dimensionality of the base model is insufficient for capturing the intricate feature hierarchies present in high-resolution natural images
"""